version: 2.1

commands:
  install-npm-dependencies:
    steps:
      - restore_cache:
          name: Restore NPM dependencies
          keys:
            - npm-{{ checksum "package.json" }}
            - npm-
      - run:
          name: Install NPM dependencies
          command: npm install
      - save_cache:
          name: Save NPM dependencies
          paths:
            - ./node_modules/
          key: npm-{{ checksum "package.json" }}

  build-all:
    steps:
      - run:
          name: Build telephone
          command: npm run build --prefix packages/telephone
      - run:
          name: Build www
          command: npm run build --prefix packages/www
jobs:
  build:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - install-npm-dependencies
      - build-all

  release:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - install-npm-dependencies
      - build-all
      - run:
          name: Publish www
          command: sh .circleci/gh-pages.sh
      - run:
          name: Release @sneas/telephone
          command: npx -w @sneas/telephone semantic-release

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
  release:
    jobs:
      - release:
          filters:
            branches:
              only: main
